data_folder_path: data/
logs_folder_path: logs/
dataset_path: data/data.csv
images_folder_path: data/images/
train_data_folder_path: data/train/
val_data_folder_path: data/val/
test_data_folder_path: data/test/
artefacts_folder_path: artefacts/
train_split: 0.7
val_split: 0.1
batch_size: 32
num_epochs: 100
learning_rate: 0.001
kaggle_dataset_path: allandclive/chicken-disease-1