log_folder_path: logs/
data_path: data/data.csv
images_folder_path: data/images/
artefacts_folder_path: artefacts/
train_split: 0.7
val_split: 0.1
batch_size: 32
num_epochs: 100
learning_rate: 0.001
kaggle_dataset_path: allandclive/chicken-disease-1