version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./app/backend:/app

  frontend:
    build:
      context: ./app/frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
