version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: app/frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
