apiVersion: v1
kind: Service
metadata:
  name: disease-classification
spec:
  selector:
    app: disease-classification
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: frontend
      port: 8501
      targetPort: 8501
  type: NodePort 